### ISSUE TITLE
ERROR ON INSTALLING REQUIREMENTS

### ISSUE THREAD

**Issue by 3th1cyuk1** [0x240x23elu/JSScanner#3]
Hi,

When I tried to use your tool by the following comand ( pip3 install -r requirements.txt ) it gives the following error !

ERROR: Could not find a version that satisfies the requirement sys (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for sys (from -r requirements.txt (line 3))

Thank You

**Comment by 0x240x23elu** [comment]
sys already installed
