### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Shahad7278** [0x240x23elu/JSScanner#5]
python3 -m pip install -r  requirements.txtRequirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.23.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (1.25.9)
ERROR: Could not find a version that satisfies the requirement sys
ERROR: No matching distribution found for sys

**Comment by 0x240x23elu** [comment]
sys already installed
